### ISSUE TITLE
where to specify path to BAMs

### ISSUE THREAD

**Issue by domivika** [ClarkLaboratory/IsoLamp#8]
Hello,

Another question I have is where to specify the path to BAM files if I already have them mapped and want to run isoform discovery modules as specified here:

`# isoform discovery modules only (requires BAMs)`
`IsoLamp -p params.ini -m isoform_discovery`

My BAM files are stored in the same directories as FASTQ files.

Thanks!

**Comment by domivika** [comment]
Found it! I didn't notice it has to be finished with _primary_merged

> function set_skip_mapping_vars() {
> 	
> 	if ! test -f $OUTPUT_NAME/mapped_data/${OUTPUT_NAME}_primary_merged.bam
> 	then
> 		echo "No BAM file found, run mapping first."
> 		exit 1
> 	fi

**Comment by josiegleeson** [comment]
Hi, yes this module assumes you've ran the mapping with IsoLamp... I might try and update the documentation so this is easier for future use.

But you're correct, the BAM file path will be:
'OUTPUT_NAME/mapped_data/OUTPUT_NAME_primary_merged.bam and it needs to be sorted and indexed.

Thanks!
